// Mock Notifications Data - Finance Pulse Demo

export type NotificationType = 
  | "invoice_due_soon"
  | "budget_warning"
  | "payment_received"
  | "report_ready"
  | "task_assigned"
  | "system";

export type NotificationPriority = "low" | "medium" | "high";

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  timestamp: string;
  isRead: boolean;
  priority: NotificationPriority;
}

export const demoNotifications: Notification[] = [
  {
    id: "1",
    type: "invoice_due_soon",
    title: "Invoice due tomorrow",
    body: "Salesforce Enterprise - $12,500",
    timestamp: "2 hours ago",
    isRead: false,
    priority: "high",
  },
  {
    id: "2",
    type: "budget_warning",
    title: "Engineering at 92% budget",
    body: "Approaching monthly limit",
    timestamp: "5 hours ago",
    isRead: false,
    priority: "medium",
  },
  {
    id: "3",
    type: "payment_received",
    title: "Payment received",
    body: "Client ABC Corp - $28,500",
    timestamp: "1 day ago",
    isRead: false,
    priority: "low",
  },
  {
    id: "4",
    type: "report_ready",
    title: "Q3 Report ready for review",
    body: "Generated by Sarah Chen",
    timestamp: "1 day ago",
    isRead: true,
    priority: "medium",
  },
  {
    id: "5",
    type: "task_assigned",
    title: "New task assigned",
    body: "Prepare variance analysis",
    timestamp: "2 days ago",
    isRead: true,
    priority: "low",
  },
  {
    id: "6",
    type: "budget_warning",
    title: "Marketing underspending",
    body: "Only 45% of budget utilized",
    timestamp: "3 days ago",
    isRead: true,
    priority: "low",
  },
  {
    id: "7",
    type: "system",
    title: "System maintenance scheduled",
    body: "Oct 30, 2am-4am EST",
    timestamp: "4 days ago",
    isRead: true,
    priority: "low",
  },
  {
    id: "8",
    type: "invoice_due_soon",
    title: "3 invoices due this week",
    body: "Total: $24,150",
    timestamp: "5 days ago",
    isRead: true,
    priority: "medium",
  },
];

export const notificationTypeIcons: Record<NotificationType, string> = {
  invoice_due_soon: "FileText",
  budget_warning: "AlertTriangle",
  payment_received: "DollarSign",
  report_ready: "FileCheck",
  task_assigned: "ListTodo",
  system: "Settings",
};

export const notificationFilters = [
  { value: "all", label: "All" },
  { value: "alerts", label: "Alerts" },
  { value: "updates", label: "Updates" },
];
